### ISSUE TITLE
Error at new user creation 

### ISSUE THREAD

**Issue by nidheeshmca** [Platformus/Platformus-Sample-Personal-Website#1]
When I am going to create a new user and assigning content manager role to him. 
Application giving error at login "HTTP Error 404.15 - Not Found
The request filtering module is configured to deny a request where the query string is too long."
**Detailed Error Information:**

Module | RequestFilteringModule
Notification | BeginRequest
Handler | aspNetCore
Error Code | 0x00000000

Requested URL :  http://birdcms.com:80/backend/account/accessdenied?next=%2Fbackend%2Faccount%2Faccessdenied%3Fnext%3D%252Fbackend%252Faccount%252Faccessdenied%253Fnext%253D%25252Fbackend%25252Faccount%25252Faccessdenied%25253Fnext%25253D%2525252Fbackend%2525252Faccount%2525252Faccessdenied%2525253Fnext%2525253D%252525252Fbackend%252525252Faccount%252525252Faccessdenied%252525253Fnext%252525253D%25252525252Fbackend%25252525252Faccount%25252525252Faccessdenied%25252525253Fnext%25252525253D%2525252525252Fbackend%2525252525252Faccount%2525252525252Faccessdenied%2525252525253Fnext%2525252525253D%252525252525252Fbackend%252525252525252Faccount%252525252525252Faccessdenied%252525252525253Fnext%252525252525253D%25252525252525252Fbackend%25252525252525252Faccount%25252525252525252Faccessdenied%25252525252525253Fnext%25252525252525253D%2525252525252525252Fbackend%2525252525252525252Faccount%2525252525252525252Faccessdenied%2525252525252525253Fnext%2525252525252525253D%252525252525252525252Fbackend%252525252525252525252Faccount%252525252525252525252Faccessdenied%252525252525252525253Fnext%252525252525252525253D%25252525252525252525252Fbackend%25252525252525252525252Faccount%25252525252525252525252Faccessdenied%25252525252525252525253Fnext%25252525252525252525253D%2525252525252525252525252Fbackend%2525252525252525252525252Faccount%2525252525252525252525252Faccessdenied%2525252525252525252525253Fnext%2525252525252525252525253D%252525252525252525252525252Fbackend%252525252525252525252525252Faccount%252525252525252525252525252Faccessdenied%252525252525252525252525253Fnext%252525252525252525252525253D%25252525252525252525252525252Fbackend%25252525252525252525252525252Faccount%25252525252525252525252525252Faccessdenied%25252525252525252525252525253Fnext%25252525252525252525252525253D%2525252525252525252525252525252Fbackend%2525252525252525252525252525252Faccount%2525252525252525252525252525252Faccessdenied%2525252525252525252525252525253Fnext%2525252525252525252525252525253D%252525252525252525252525252525252Fbackend%252525252525252525252525252525252Faccount%252525252525252525252525252525252Fsignout

Physical Path  :  C:\Users\Admin\Desktop\CorePublish\backend\account\accessdenied

**Comment by DmitrySikorsky** [comment]
Basically, you can see this huge URL and strange error because of the Platformus bug. It appears when a user is logged in, but doesn't have Browse backend permission. So you need to delete the  cookies, log in as administrator, assign appropriate role to the new user, and then login again. You will have no error. It is fix in the new version, so you will see the correct "access denied" page.
